#!/bin/bash

if [ ! -f /data/.init.accumulo ]
then
    /usr/local/accumulo/bin/accumulo init --instance-name accumulo --password accumulo
    mkdir -p /data
    touch /data/.init.accumulo
fi

uname -n > /usr/local/accumulo/conf/gc
uname -n > /usr/local/accumulo/conf/masters
uname -n > /usr/local/accumulo/conf/monitor
uname -n > /usr/local/accumulo/conf/slaves
uname -n > /usr/local/accumulo/conf/tracers

/usr/local/accumulo/bin/start-all.sh

while true
do
    sleep 100000
done
