#!/bin/bash

rewrite() {
    cat $1 | \
	sed \
	    -e "s#@ZOOKEEPERS@#${ZOOKEEPERS}#" \
	    -e "s#@HDFS_VOLUMES@#${HDFS_VOLUMES}#" \
	    -e "s#@SECRET@#${SECRET}#" \
	    > $1.tmp
    mv -f $1.tmp $1
}

ZOOKEEPERS=${ZOOKEEPERS:-zookeeper:2181}
MY_HOSTNAME=${MY_HOSTNAME:-localhost}
HDFS_VOLUMES=${HDFS_VOLUMES:-file:/accumulo}
NAMENODE_URI=${NAMENODE_URI:-}
INSTANCE_NAME=${INSTANCE_NAME:-accumulo}
SECRET=${SECRET:-accumulo}

rewrite ${ACCUMULO_HOME}/conf/accumulo-site.xml

if [ ! -f /accumulo/.init.accumulo ]
then
    echo 'Initialise accumulo...'
    /usr/local/accumulo/bin/accumulo init --instance-name ${INSTANCE_NAME} \
        --password ${SECRET} --clear-instance-name
    mkdir -p /data
    touch /accumulo/.init.accumulo
fi

(
    for v in $(echo ${GC_HOSTS} | sed 's/,/ /g')
    do
	echo $v
    done
) > /usr/local/accumulo/conf/gc

(
    for v in $(echo ${MASTER_HOSTS} | sed 's/,/ /g')
    do
	echo $v
    done
) > /usr/local/accumulo/conf/masters

(
    for v in $(echo ${SLAVE_HOSTS} | sed 's/,/ /g')
    do
	echo $v
    done
) > /usr/local/accumulo/conf/slaves

(
    for v in $(echo ${MONITOR_HOSTS} | sed 's/,/ /g')
    do
	echo $v
    done
) > /usr/local/accumulo/conf/monitor

(
    for v in $(echo ${TRACER_HOSTS} | sed 's/,/ /g')
    do
	echo $v
    done
) > /usr/local/accumulo/conf/tracers

(
  echo "<configuration>"
  echo "  <property>"
  echo "    <name>fs.defaultFS</name>"
  echo "    <value>${NAMENODE_URI}</value>"
  echo "  </property>"
  echo "</configuration>"
) > /usr/local/hadoop/etc/hadoop/core-site.xml

(
    for v in $(echo ${DAEMONS} | sed 's/,/ /g')
    do
	echo Starting $v...
	/usr/local/accumulo/bin/start-daemon.sh ${MY_HOSTNAME} $v
    done
)

while true
do
    sleep 100000
done

